import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Typography from "@mui/material/Typography";
import Paper from "@mui/material/Paper";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Avatar from "@mui/material/Avatar";

import dayjs from "dayjs";

//Fix the onClick, at the moment it just console.logs('clicked)

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
    date: new Date("02/28/2023").getTime(),
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
    date: new Date("02/28/2023").getTime(),
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
    date: new Date("02/27/2023").getTime(),
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
    date: new Date("02/27/2023").getTime(),
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
    date: new Date("02/26/2023").getTime(),
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
    date: new Date("03/01/2023").getTime(),
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
    date: new Date("01/29/2023").getTime(),
  },
];

const MessagesList = ({ input }) => {
  const today = dayjs(Date.now()).format("DD/MM/YYYY");

  const yesterday = dayjs(new Date().setDate(new Date().getDate() - 1)).format(
    "DD/MM/YYYY"
  );
  const lastWeekEnd = new Date().setDate(new Date().getDate() - 2);
  const lastWeekStart = new Date().setDate(new Date().getDate() - 5);

  
  const messageList = {
    Today: messages?.filter(
      (message) => dayjs(message.date).format("DD/MM/YYYY") === today
    ),

    Yesterday: messages?.filter(
      (message) => dayjs(message.date).format("DD/MM/YYYY") === yesterday
    ),
    Last_Week: messages?.filter(
      (message) =>
        new Date(dayjs(message.date).format("MM/DD/YYYY")) >= lastWeekStart &&
        new Date(dayjs(message.date).format("MM/DD/YYYY")) <= lastWeekEnd
    ),
    Older_Messages: messages?.filter(
      (message) =>
        new Date(dayjs(message.date).format("MM/DD/YYYY")) < lastWeekStart
    ),
  };

  const AllMessages = Object.entries(messageList).map((el) => {
    return (
      <div key={el[0]}>
        <ListSubheader  sx={{ bgcolor: "background.paper" }}>
          {el[0].split("_").join(" ")}
        </ListSubheader>
        {el[1].map(({ id, primary, secondary, person, date }) => (
          <React.Fragment key={id}>
            <ListItem onClick={() => console.log('clicked')}>
              <ListItemAvatar>
                <Avatar alt="Profile Picture" src={person} />
              </ListItemAvatar>
              <ListItemText primary={primary} secondary={secondary} />
            </ListItem>
          </React.Fragment>
        ))}
      </div>
    );
  });

  return (
    <>
      <CssBaseline />
      <Paper square sx={{ pb: "50px" }}>
        <Typography
          variant="h5"
          gutterBottom
          component="div"
          sx={{ p: 2, pb: 0 }}
        >
          Inbox
        </Typography>
        <List sx={{ mb: 2 }}>{AllMessages}</List>
      </Paper>
    </>
  );
};

export default MessagesList;
