import * as React from 'react';
import {Accordion, Box} from '@mui/material';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import CircleIcon from '@mui/icons-material/Circle';

export default function ControlledAccordions() {
  const [expanded, setExpanded] = React.useState(false);

  const handleChange = (panel) => (event, isExpanded) => {
    setExpanded(isExpanded ? panel : false);
  };

  const Title = ({data}) => {
    return (
        <Box sx={{display: 'flex', alignItems: 'center'}}>
        <CircleIcon sx={{fontSize:15}}/> <Typography sx={{ml:2}}>{data}</Typography>
        </Box>
    )
  }



  const accordionData = [
    {
        title: <Title data={'Solar Energy Captured'}/>,
        secondary: ' How Solar Panels Convert Sunlight to Electricity',
        text: 'Solar panels on your roof capture energy from the sun and convert it into electricity.'
    },
    {
        title: <Title data={'Inverter'}/>,
        secondary: 'The Device That Transforms DC Electricity to AC Electricity for Household Use',
        text: 'This electricity is then sent to an inverter, which converts it from DC (direct current) to AC (alternating current) that can be used to power your home.'
    },
    {
        title: <Title data={'Battery Storage'}/>,
        secondary: 'What Happens to Excess Solar Energy?',
        text: 'Any excess energy generated by the solar panels that is not immediately used by your home is sent to a battery for storage.'
    },
    {
        title: <Title data={'Battery Backup'}/>,
        secondary: 'Powering Your Home Even When the Sun Is Not Shining',
        text: 'When your home needs energy at night or when the sun is not shining, the stored energy in the battery is used to power your home.'
    }, {
        title: <Title data={'Excess Energy'}/>,
        secondary: 'Selling Back to the Grid and Getting Credits',
        text: 'If the battery is fully charged and there is still excess energy being generated by the solar panels, it can be sent back to the grid to receive credits or sold to your utility company.'
    }, {
        title: <Title data={'Solar Monitoring'}/>,
        secondary: 'Tracking and Optimising Your Energy Savings',
        text: 'The entire process is monitored and managed by a solar monitoring system that tracks energy production, usage, and storage, allowing you to optimize your energy savings and reduce your carbon footprint.'
    },
]

  return (
    <div>

        {accordionData.map((el, index) => {
            return (
                <Accordion key={index} expanded={expanded === `panel${index+1}`} onChange={handleChange('panel1')}>
                <AccordionSummary
                  expandIcon={<ExpandMoreIcon />}
                  aria-controls="panel1bh-content"
                  id="panel1bh-header"
                >
                  <Typography sx={{ width: '33%', flexShrink: 0 }}>
                    {el.title}
                  </Typography>
                  <Typography sx={{ color: 'text.secondary' }}>{el.secondary}</Typography>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography>
                    {el.text}
                  </Typography>
                </AccordionDetails>
              </Accordion>
            )
            
            
        })}
    </div>
  );
}
